In [2]:
import pickle
import numpy as np

In [4]:
ohe_sex = pickle.load(open('model/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('model/ohe_embarked.pkl','rb'))
clf = pickle.load(open('model/clf.pkl','rb'))

d:\100DaysOfML\mlenv\Lib\site-packages\sklearn\base.py:376: InconsistentVersionWarning: Trying to unpickle estimator OneHotEncoder from version 0.23.1 when using version 1.4.1.post1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(


ValueError: node array from the pickle has an incompatible dtype:
- expected: {'names': ['left_child', 'right_child', 'feature', 'threshold', 'impurity', 'n_node_samples', 'weighted_n_node_samples', 'missing_go_to_left'], 'formats': ['<i8', '<i8', '<i8', '<f8', '<f8', '<i8', '<f8', 'u1'], 'offsets': [0, 8, 16, 24, 32, 40, 48, 56], 'itemsize': 64}
- got     : [('left_child', '<i8'), ('right_child', '<i8'), ('feature', '<i8'), ('threshold', '<f8'), ('impurity', '<f8'), ('n_node_samples', '<i8'), ('weighted_n_node_samples', '<f8')]

In [21]:
# Assume user input
# Pclass/gender/age/SibSp/Parch/Fare/Embarked
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1,7)

In [22]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [23]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

In [24]:
test_input_sex

array([[0., 1.]])

In [25]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [26]:
test_input_embarked

array([[0., 0., 1.]])

In [14]:
test_input_age = test_input[:,2].reshape(1,1)

In [27]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [28]:
test_input_transformed.shape

(1, 10)

In [29]:
clf.predict(test_input_transformed)

array([1], dtype=int64)